// notifications.js — per-user notifications with read state, pushed live over the
// SSE hub that already exists (events.js). Before this, boards were told nothing:
// the topbar bell was a hardcoded "8", and a seller clicking "Talk to a human" only
// posted a chat message nobody was alerted to.
//
// Design notes:
//  - Fan-out on WRITE (a row per recipient). Reads are the hot path — every board
//    polls/streams its own bell — and "unread for me" must be a primary-key hit,
//    not a scan with a join.
//  - notify() is fire-and-forget by contract: a notification must NEVER fail the
//    business action that triggered it (shipping an order, sending a message).
import { q } from '../db.js';
import { egBroadcast } from '../events.js';

let _ready = null;
export function ensureNotifications() {
  if (_ready) return _ready;
  _ready = q(`create table if not exists notifications (
    id          bigint generated by default as identity primary key,
    user_id     uuid references users(id) on delete cascade,
    type        text not null,
    title       text not null,
    body        text,
    href        text,
    entity_id   text,
    read_at     timestamptz,
    created_at  timestamptz not null default now()
  )`)
    .then(() => q('create index if not exists notifications_user_idx on notifications (user_id, created_at desc)'))
    // Partial index: the badge count only ever asks for UNREAD, and unread stays small.
    .then(() => q('create index if not exists notifications_unread_idx on notifications (user_id) where read_at is null'))
    .catch((e) => { _ready = null; throw e; });
  return _ready;
}

// Who should hear about a factory-side event? Staff roles, minus anyone opted out.
async function staffIds(roles) {
  const r = await q(
    `select id from users where active is not false and role = any($1::text[])`,
    [roles]
  );
  return r.rows.map((x) => x.id);
}

/**
 * Create notifications and push them live.
 *   notify({ userIds | roles, type, title, body, href, entityId })
 * Never throws — callers use it fire-and-forget.
 */
export async function notify({ userIds, roles, type, title, body, href, entityId }) {
  try {
    await ensureNotifications();
    let ids = Array.isArray(userIds) ? userIds.filter(Boolean) : [];
    if (roles && roles.length) ids = ids.concat(await staffIds(roles));
    ids = Array.from(new Set(ids.map(String))).filter(Boolean);
    if (!ids.length) return;

    await q(
      `insert into notifications (user_id, type, title, body, href, entity_id)
       select unnest($1::uuid[]), $2, $3, $4, $5, $6`,
      [ids, type, String(title).slice(0, 200), body ? String(body).slice(0, 500) : null, href || null, entityId ? String(entityId) : null]
    );
    // The SSE hub is a broadcast bus with no per-user routing, so carry the intended
    // recipients and let each client ignore what isn't theirs.
    egBroadcast({ type: 'notification', users: ids, kind: type, title });
  } catch (e) {
    // Swallow: a missed bell must never break the action that caused it.
  }
}

export function notificationRoutes(app, requireAuth) {
  ensureNotifications().catch(() => {});

  // The bell: recent notifications + unread count.
  app.get('/api/notifications', { preHandler: requireAuth }, async (req) => {
    await ensureNotifications();
    const limit = Math.min(50, Math.max(1, Number(req.query?.limit) || 20));
    const r = await q(
      `select id, type, title, body, href, entity_id, read_at, created_at
         from notifications where user_id=$1 order by created_at desc limit $2`,
      [req.user.sub, limit]
    );
    const c = await q('select count(*)::int as n from notifications where user_id=$1 and read_at is null', [req.user.sub]);
    return { unread: c.rows[0]?.n || 0, notifications: r.rows };
  });

  // Mark one read, or all when no id is given.
  app.post('/api/notifications/read', { preHandler: requireAuth }, async (req) => {
    await ensureNotifications();
    const id = req.body && req.body.id;
    if (id) await q('update notifications set read_at=now() where user_id=$1 and id=$2 and read_at is null', [req.user.sub, id]);
    else await q('update notifications set read_at=now() where user_id=$1 and read_at is null', [req.user.sub]);
    const c = await q('select count(*)::int as n from notifications where user_id=$1 and read_at is null', [req.user.sub]);
    return { ok: true, unread: c.rows[0]?.n || 0 };
  });
}
