import { q } from './db.js';

/**
 * A DESIGN ID, ISSUED AUTOMATICALLY — DSN-1001.
 *
 * Nothing assigned one before. `order_designs` had no id column at all (its identity is
 * (order, line, kind)), `design_cards.design_id` was filled on 3 rows of 20, and the most
 * recent Pink Design submission carried none. So the only way to refer to a piece of
 * artwork was the file name someone happened to type, which is a naming convention — the
 * thing this removes.
 *
 * KEYED ON THE ARTWORK, NOT THE UPLOAD. This is the decision that makes the number worth
 * having. The same design placed on twelve orders gets ONE id, because the id is derived
 * from art_hash — the exact content hash already computed and indexed on every upload. So
 * searching DSN-1042 finds every order printing that artwork, which is what "batch similar
 * designs for faster production" actually needs. An id per upload would give twelve
 * different numbers for one job and answer nothing.
 *
 * Two consequences worth stating:
 *   - Re-uploading the same file to a new order reuses its number rather than minting one.
 *     That is the point, not a collision.
 *   - A design edited even slightly is different artwork and gets a NEW number. art_hash is
 *     exact; art_phash (fuzzy) exists for "looks similar" and deliberately does NOT feed
 *     this, because an id that quietly merged two near-identical designs would send the
 *     wrong file to the machine.
 */

/** Numbers start here so an early design and a thousandth read and sort alike, and nothing
 *  collides with the small ids used elsewhere. Mirrors the EG- product SKUs. */
const FIRST = 1001;

let _ready = null;
export function ensureDesignIds() {
  if (_ready) return _ready;
  _ready = q(`create table if not exists design_ids (
       art_hash   text primary key,
       design_no  bigint generated by default as identity (start with ${FIRST}) not null unique,
       first_seen timestamptz not null default now(),
       /** Where it turned up first — for "what was this originally for", nothing more. */
       first_order_id text
     )`)
    .catch((e) => { _ready = null; throw e; });
  return _ready;
}

/** The public form. One place, so a number reads identically everywhere it appears. */
export const designLabel = (n) => (n == null ? null : `DSN-${n}`);

/**
 * The id for this artwork, minting one on first sight.
 *
 * Returns null for artwork with no hash — an older row, or a path that never computed one.
 * A null is honest; inventing a number for artwork we can't fingerprint would hand the same
 * id to every unfingerprinted design on the system.
 *
 * ON CONFLICT DO NOTHING then select, rather than a read-then-write: two uploads of the
 * same file landing together would otherwise both find nothing and both insert.
 */
export async function designNoFor(artHash, orderId = null) {
  const h = String(artHash || '').trim();
  if (!h) return null;
  try {
    await ensureDesignIds();
    await q(
      `insert into design_ids (art_hash, first_order_id) values ($1,$2)
       on conflict (art_hash) do nothing`,
      [h, orderId || null]
    );
    const r = await q('select design_no from design_ids where art_hash=$1', [h]);
    return r.rows[0] ? Number(r.rows[0].design_no) : null;
  } catch {
    // Never fail the upload over its label. Artwork landing matters; its number does not.
    return null;
  }
}

/** Numbers for many hashes at once — one query, for list routes that would otherwise ask
 *  per line. Returns a map of art_hash → design_no for those already issued; it does NOT
 *  mint, because a read of a list is not the moment to write. */
export async function designNosFor(hashes) {
  const list = [...new Set((hashes || []).map((h) => String(h || '').trim()).filter(Boolean))];
  if (!list.length) return {};
  try {
    await ensureDesignIds();
    const r = await q('select art_hash, design_no from design_ids where art_hash = any($1::text[])', [list]);
    return Object.fromEntries(r.rows.map((x) => [x.art_hash, Number(x.design_no)]));
  } catch {
    return {};
  }
}
