-- ============================================================================
-- EGFULFILL — plain PostgreSQL schema for the self-hosted backend.
-- Runs automatically on first `docker compose up` (mounted into Postgres).
-- No Supabase auth/RLS here — your API enforces permissions in code instead.
-- ============================================================================
create extension if not exists "pgcrypto";   -- gen_random_uuid()

-- Users (replaces Supabase auth.users + profiles)
create table if not exists users (
  id            uuid primary key default gen_random_uuid(),
  email         text unique not null,
  password_hash text not null,
  role          text not null default 'seller',   -- seller|operator|admin|warehouse|designer
  name          text,
  store_name    text,
  active        boolean not null default true,     -- false = deactivated (login blocked, data kept)
  created_at    timestamptz default now()
);

create table if not exists orders (
  id              text primary key,
  seller_id       uuid references users(id) on delete set null,
  store           text,
  source          text default 'manual',
  seq             integer,
  meta            jsonb default '{}',
  customer        jsonb default '{}',
  address         jsonb default '{}',
  status          text default 'new',
  factory_status  text default 'new',
  total           numeric default 0,
  profit          numeric default 0,
  delivery        text,
  carrier         text,
  service         text,
  tracking        text,
  tracking_label_url text,
  timeline        jsonb default '[]',
  notes           jsonb default '[]',
  gates           jsonb default '{}',
  est_delivery    date,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index if not exists orders_seller_idx on orders(seller_id);

create table if not exists order_items (
  id             uuid primary key default gen_random_uuid(),
  order_id       text references orders(id) on delete cascade,
  sku text, name text, listing text, print_type text,
  qty int default 1, color text, size text, variant text, blank text,
  unit_price numeric default 0, design_src text, factory_status text default '',
  threads jsonb default '[]', design_pos jsonb, img text,
  created_at timestamptz default now()
);
create index if not exists order_items_order_idx on order_items(order_id);

create table if not exists design_cards (
  id bigint generated by default as identity primary key,
  order_id text references orders(id) on delete cascade,
  sku text, design_id text, title text, col text default 'incoming', type text, product text,
  priority text default 'normal', due date, assignee text, claimed_by text,
  payment numeric default 0, pay_status text default 'pending',
  is_emb boolean default false, emb_file_name text, thumb text, thumb_ref text,
  files jsonb default '[]', specs jsonb default '{}', notes jsonb default '[]',
  history jsonb default '[]', checklist jsonb default '[]',
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists inventory (
  sku text primary key, name text, variant text,
  in_stock int default 0, reserved int default 0, reorder_at int default 25,
  category text, updated_at timestamptz default now()
);

create table if not exists catalog_products (
  id text primary key, name text not null, sku text, type text, method text,
  status text default 'Active', base_price numeric default 0, price numeric default 0,
  variant_skus jsonb default '[]', size_prices jsonb default '[]',
  color_images jsonb default '{}', side_mockups jsonb default '{}',
  mockup_path text, img_path text, main_color text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

-- Connected sales channels (Etsy, etc.). One row per shop; OAuth tokens stored
-- here (refreshed automatically). Supports several shops under one account.
create table if not exists platform_connections (
  id uuid primary key default gen_random_uuid(),
  platform text not null default 'etsy',
  shop_id text not null,
  shop_name text,
  access_token text,
  refresh_token text,
  token_expires_at timestamptz,
  scopes text,
  last_sync_at timestamptz,
  connected_by uuid references users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (platform, shop_id)
);

create table if not exists backorders (
  id uuid primary key default gen_random_uuid(),
  order_id text references orders(id) on delete cascade,
  items jsonb default '[]', status text default 'open', created_at timestamptz default now()
);
create table if not exists purchase_orders (
  num text primary key, supplier text, items jsonb default '[]',
  status text default 'draft', total numeric default 0, created_at timestamptz default now()
);

create table if not exists wallets (
  owner_id uuid primary key references users(id) on delete cascade,
  balance numeric default 0, updated_at timestamptz default now()
);
create table if not exists ledger (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references users(id) on delete cascade,
  type text, amount numeric not null, card_id bigint, order_id text,
  label text, created_by text, created_at timestamptz default now()
);

create table if not exists order_messages (
  id uuid primary key default gen_random_uuid(),
  order_id text references orders(id) on delete cascade,
  sender_id uuid references users(id) on delete set null,
  sender_role text, body text, attachment jsonb, created_at timestamptz default now()
);

create table if not exists scan_history (
  id uuid primary key default gen_random_uuid(),
  sku text, direction text, qty int default 1, order_ref text,
  by_id uuid references users(id) on delete set null, created_at timestamptz default now()
);

create table if not exists design_files (
  order_id text, sku text, kind text, storage_path text, file_name text, mime text,
  created_at timestamptz default now(), primary key (order_id, sku, kind)
);

create table if not exists settings (
  key text primary key, value jsonb, updated_at timestamptz default now()
);
insert into settings (key, value) values
  ('eg_designer_fee_rate','2.5'), ('eg_default_shipping_fee','5'), ('eg_default_addl_item_fee','2')
on conflict (key) do nothing;
